name: Run Monitoring Pipeline

on:
  push: {}
#  pull_request:
#    types: [opened, synchronize, reopened]
#    branches: [main]
  workflow_dispatch: {}

jobs:
  Wait-for-images:
    runs-on: ubuntu-latest
    outputs:
      conclusion: ${{ steps.wait.outputs.conclusion }}
    steps:
      - name: Wait for build.yaml to complete
        uses: netcracker/qubership-workflow-hub/actions/wait-for-workflow@release/v2.0.5
        id: wait
        with:
          workflow: build.yaml
          token: ${{ secrets.GITHUB_TOKEN }}

  Monitoring-Pipeline:
    needs: Wait-for-images
    if: ${{ needs.Wait-for-images.outputs.conclusion }} == 'success'
    uses: Netcracker/qubership-test-pipelines/.github/workflows/monitoring.yaml@monitoring
    with:
      service_branch: '${{ github.head_ref || github.ref_name }}'
      versions_file: '.github/versions.yaml'
      pipeline_branch: 'monitoring' #this value must match the value after '@' in 'uses'
      repository_name: 'Netcracker/qubership-monitoring-operator'

